// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Usage", "MA0004:Use Task.ConfigureAwait(false)", Justification = "<Pending>", Scope = "member", Target = "~M:KOTORModSync.Core.Services.CrossPlatformFileLock.LockAsync~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Usage", "MA0004:Use Task.ConfigureAwait(false)", Justification = "<Pending>", Scope = "member", Target = "~M:KOTORModSync.Core.Services.CrossPlatformFileLock.LockUnixFileAsync~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Usage", "MA0004:Use Task.ConfigureAwait(false)", Justification = "<Pending>", Scope = "member", Target = "~M:KOTORModSync.Core.Services.CrossPlatformFileLock.UnlockAsync~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Usage", "MA0004:Use Task.ConfigureAwait(false)", Justification = "<Pending>", Scope = "member", Target = "~M:KOTORModSync.Core.Services.CrossPlatformFileLock.UnlockUnixFileAsync~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Usage", "MA0004:Use Task.ConfigureAwait(false)", Justification = "<Pending>", Scope = "member", Target = "~M:KOTORModSync.Core.Services.Download.DeadlyStreamDownloadHandler.GetFileMetadataAsync(System.String,System.Threading.CancellationToken)~System.Threading.Tasks.Task{System.Collections.Generic.Dictionary{System.String,System.Object}}")]
[assembly: SuppressMessage("Usage", "MA0004:Use Task.ConfigureAwait(false)", Justification = "<Pending>", Scope = "member", Target = "~M:KOTORModSync.Core.Services.Download.DeadlyStreamDownloadHandler.ResolveFilenameFromLink(System.String,System.Threading.CancellationToken)~System.Threading.Tasks.Task{System.String}")]
[assembly: SuppressMessage("Usage", "MA0004:Use Task.ConfigureAwait(false)", Justification = "<Pending>", Scope = "member", Target = "~M:KOTORModSync.Core.Services.Download.DeadlyStreamDownloadHandler.ResolveFilenamesAsync(System.String,System.Threading.CancellationToken)~System.Threading.Tasks.Task{System.Collections.Generic.List{System.String}}")]
[assembly: SuppressMessage("Usage", "MA0004:Use Task.ConfigureAwait(false)", Justification = "<Pending>", Scope = "member", Target = "~M:KOTORModSync.Core.Services.DownloadCacheService.AnalyzeDownloadNecessityWithStatusAsync(KOTORModSync.Core.ModComponent,System.String,System.Threading.CancellationToken)~System.Threading.Tasks.Task{System.ValueTuple{System.Collections.Generic.List{System.String},System.Boolean}}")]
[assembly: SuppressMessage("Usage", "MA0004:Use Task.ConfigureAwait(false)", Justification = "<Pending>", Scope = "member", Target = "~M:KOTORModSync.Core.Services.DownloadCacheService.CheckCacheAndFileExistenceAsync(System.String,KOTORModSync.Core.ModComponent,System.String,System.String,System.IProgress{KOTORModSync.Core.Services.Download.DownloadProgress},System.Threading.CancellationToken)~System.Threading.Tasks.Task{System.ValueTuple{System.String,KOTORModSync.Core.Services.DownloadCacheService.DownloadCacheEntry,System.Boolean}}")]
[assembly: SuppressMessage("Usage", "MA0004:Use Task.ConfigureAwait(false)", Justification = "<Pending>", Scope = "member", Target = "~M:KOTORModSync.Core.Services.DownloadCacheService.ClearCacheAsync(System.String)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Usage", "MA0004:Use Task.ConfigureAwait(false)", Justification = "<Pending>", Scope = "member", Target = "~M:KOTORModSync.Core.Services.DownloadCacheService.EnsureInstructionsExist(KOTORModSync.Core.ModComponent,System.Collections.Generic.List{KOTORModSync.Core.Services.DownloadCacheService.DownloadCacheEntry},System.Threading.CancellationToken)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Usage", "MA0004:Use Task.ConfigureAwait(false)", Justification = "<Pending>", Scope = "member", Target = "~M:KOTORModSync.Core.Services.DownloadCacheService.InitializeVirtualFileSystemAsync(System.String)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Usage", "MA0004:Use Task.ConfigureAwait(false)", Justification = "<Pending>", Scope = "member", Target = "~M:KOTORModSync.Core.Services.DownloadCacheService.LoadResourceIndexAsync~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Usage", "MA0004:Use Task.ConfigureAwait(false)", Justification = "<Pending>", Scope = "member", Target = "~M:KOTORModSync.Core.Services.DownloadCacheService.PopulateModLinkFilenamesWithSimulationAsync(KOTORModSync.Core.ModComponent,System.String,System.Collections.Generic.List{System.String},System.String)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Usage", "MA0004:Use Task.ConfigureAwait(false)", Justification = "<Pending>", Scope = "member", Target = "~M:KOTORModSync.Core.Services.DownloadCacheService.PreResolveUrlsAsync(KOTORModSync.Core.ModComponent,KOTORModSync.Core.Services.Download.DownloadManager,System.Boolean,System.Threading.CancellationToken)~System.Threading.Tasks.Task{System.Collections.Generic.Dictionary{System.String,System.Collections.Generic.List{System.String}}}")]
[assembly: SuppressMessage("Usage", "MA0004:Use Task.ConfigureAwait(false)", Justification = "<Pending>", Scope = "member", Target = "~M:KOTORModSync.Core.Services.DownloadCacheService.ProcessResolvedUrlForPreResolveAsync(KOTORModSync.Core.ModComponent,System.Collections.Generic.KeyValuePair{System.String,System.Collections.Generic.List{System.String}},System.Collections.Generic.Dictionary{System.String,System.Collections.Generic.List{System.String}},System.String,System.Collections.Generic.List{System.ValueTuple{System.String,System.String}})~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Usage", "MA0004:Use Task.ConfigureAwait(false)", Justification = "<Pending>", Scope = "member", Target = "~M:KOTORModSync.Core.Services.DownloadCacheService.ResolveOrDownloadAsync(KOTORModSync.Core.ModComponent,System.String,System.IProgress{KOTORModSync.Core.Services.Download.DownloadProgress},System.Boolean,System.Threading.CancellationToken)~System.Threading.Tasks.Task{System.Collections.Generic.List{KOTORModSync.Core.Services.DownloadCacheService.DownloadCacheEntry}}")]
[assembly: SuppressMessage("Usage", "MA0004:Use Task.ConfigureAwait(false)", Justification = "<Pending>", Scope = "member", Target = "~M:KOTORModSync.Core.Services.DownloadCacheService.RollbackInstructionChanges(KOTORModSync.Core.ModComponent,System.Collections.Generic.Dictionary{System.Guid,System.ValueTuple{KOTORModSync.Core.Instruction.ActionType,System.Collections.Generic.List{System.String},System.String}})~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Usage", "MA0004:Use Task.ConfigureAwait(false)", Justification = "<Pending>", Scope = "member", Target = "~M:KOTORModSync.Core.Services.DownloadCacheService.SaveResourceIndexAsync~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Usage", "MA0004:Use Task.ConfigureAwait(false)", Justification = "<Pending>", Scope = "member", Target = "~M:KOTORModSync.Core.Services.DownloadCacheService.TryFixArchiveNameMismatchAsync(KOTORModSync.Core.ModComponent,KOTORModSync.Core.Instruction,KOTORModSync.Core.Services.DownloadCacheService.DownloadCacheEntry,System.Threading.CancellationToken)~System.Threading.Tasks.Task{System.Boolean}")]
[assembly: SuppressMessage("Usage", "MA0004:Use Task.ConfigureAwait(false)", Justification = "<Pending>", Scope = "member", Target = "~M:KOTORModSync.Core.Services.DownloadCacheService.UpdateMappingWithVerification(System.String,System.String,KOTORModSync.Core.ResourceMetadata)~System.Threading.Tasks.Task{System.Boolean}")]
[assembly: SuppressMessage("Usage", "MA0004:Use Task.ConfigureAwait(false)", Justification = "<Pending>", Scope = "member", Target = "~M:KOTORModSync.Core.Services.ImmutableCheckpoint.BinaryDiffService.ApplyForwardDeltaAsync(KOTORModSync.Core.Services.ImmutableCheckpoint.FileDelta,System.String,System.Threading.CancellationToken)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Usage", "MA0004:Use Task.ConfigureAwait(false)", Justification = "<Pending>", Scope = "member", Target = "~M:KOTORModSync.Core.Services.ImmutableCheckpoint.BinaryDiffService.ApplyOctodiffDeltaAsync(System.IO.Stream,System.IO.Stream,System.String,System.Threading.CancellationToken)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Usage", "MA0004:Use Task.ConfigureAwait(false)", Justification = "<Pending>", Scope = "member", Target = "~M:KOTORModSync.Core.Services.ImmutableCheckpoint.BinaryDiffService.ApplyReverseDeltaAsync(KOTORModSync.Core.Services.ImmutableCheckpoint.FileDelta,System.String,System.Threading.CancellationToken)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Usage", "MA0004:Use Task.ConfigureAwait(false)", Justification = "<Pending>", Scope = "member", Target = "~M:KOTORModSync.Core.Services.ImmutableCheckpoint.BinaryDiffService.ComputeFileHashAsync(System.String,System.Threading.CancellationToken)~System.Threading.Tasks.Task{System.String}")]
[assembly: SuppressMessage("Usage", "MA0004:Use Task.ConfigureAwait(false)", Justification = "<Pending>", Scope = "member", Target = "~M:KOTORModSync.Core.Services.ImmutableCheckpoint.BinaryDiffService.CreateBidirectionalDeltaAsync(System.String,System.String,System.String,System.Threading.CancellationToken)~System.Threading.Tasks.Task{KOTORModSync.Core.Services.ImmutableCheckpoint.FileDelta}")]
[assembly: SuppressMessage("Usage", "MA0004:Use Task.ConfigureAwait(false)", Justification = "<Pending>", Scope = "member", Target = "~M:KOTORModSync.Core.Services.ImmutableCheckpoint.BinaryDiffService.CreateOctodiffDeltaAsync(System.String,System.String,System.IO.Stream,System.Threading.CancellationToken)~System.Threading.Tasks.Task{System.Int64}")]
