// Copyright 2021-2025 KOTORModSync
// Licensed under the GNU General Public License v3.0 (GPLv3).
// See LICENSE.txt file in the project root for full license information.

using System;
using Avalonia.Controls;
using Avalonia.Interactivity;
using Avalonia.Markup.Xaml;
using JetBrains.Annotations;

namespace KOTORModSync.Controls
{
	public partial class InstructionEditorControl : UserControl
	{
		public InstructionEditorControl() =>
		// This method is typically auto-generated by the XAML compiler
		// Adding a manual implementation as a temporary fix
		AvaloniaXamlLoader.Load(this);

		public event EventHandler<RoutedEventArgs> AddNewInstruction;
		public event EventHandler<RoutedEventArgs> DeleteInstruction;
		public event EventHandler<RoutedEventArgs> MoveInstructionUp;
		public event EventHandler<RoutedEventArgs> MoveInstructionDown;
		public event EventHandler<RoutedEventArgs> BrowseSourceFiles;
		public event EventHandler<RoutedEventArgs> BrowseSourceFromFolders;
		public event EventHandler<RoutedEventArgs> BrowseDestination;

		private void AddNewInstruction_Click([NotNull] object sender, [NotNull] RoutedEventArgs e) => AddNewInstruction?.Invoke(sender, e);

		private void DeleteInstruction_Click([NotNull] object sender, [NotNull] RoutedEventArgs e) => DeleteInstruction?.Invoke(sender, e);

		private void MoveInstructionUp_Click([NotNull] object sender, [NotNull] RoutedEventArgs e) => MoveInstructionUp?.Invoke(sender, e);

		private void MoveInstructionDown_Click([NotNull] object sender, [NotNull] RoutedEventArgs e) => MoveInstructionDown?.Invoke(sender, e);

		private void BrowseSourceFiles_Click([NotNull] object sender, [NotNull] RoutedEventArgs e) => BrowseSourceFiles?.Invoke(sender, e);

		private void BrowseSourceFromFolders_Click([NotNull] object sender, [NotNull] RoutedEventArgs e) => BrowseSourceFromFolders?.Invoke(sender, e);

		private void BrowseDestination_Click([NotNull] object sender, [NotNull] RoutedEventArgs e) => BrowseDestination?.Invoke(sender, e);
	}
}
