// Copyright 2021-2025 KOTORModSync
// Licensed under the Business Source License 1.1 (BSL 1.1).
// See LICENSE.txt file in the project root for full license information.

using System;
using Avalonia;
using Avalonia.Controls;
using Avalonia.Interactivity;
using JetBrains.Annotations;
using KOTORModSync.Core;

namespace KOTORModSync.Controls
{
	public partial class ModListSidebar : UserControl
	{
		public static readonly StyledProperty<string> SearchTextProperty =
			AvaloniaProperty.Register<ModListSidebar, string>(nameof(SearchText));

		public string SearchText
		{
			get => GetValue(SearchTextProperty);
			set => SetValue(SearchTextProperty, value);
		}

		// Events for parent to handle
		public event EventHandler<RoutedEventArgs> SelectAllRequested;
		public event EventHandler<RoutedEventArgs> DeselectAllRequested;
		public event EventHandler<RoutedEventArgs> SelectByTierRequested;
		public event EventHandler<RoutedEventArgs> ClearCategorySelectionRequested;
		public event EventHandler<RoutedEventArgs> ApplyCategorySelectionsRequested;

		public ModListSidebar()
		{
			InitializeComponent();
		}

		// Expose controls for external access
		public ListBox ModListBox => this.FindControl<ListBox>("ModListBoxElement");
		public TextBlock ModCountTextBlock => this.FindControl<TextBlock>("ModCountText");
		public TextBlock SelectedCountTextBlock => this.FindControl<TextBlock>("SelectedCountText");
		// Note: TierSelectionComboBox, CategorySelectionItemsControl, GlobalActionsButton, and ModListContextMenu
		// are now auto-generated by Avalonia from x:Name attributes in the XAML

		[UsedImplicitly]
		private void SelectAll_Click(object sender, RoutedEventArgs e)
		{
			SelectAllRequested?.Invoke(sender, e);
		}

		[UsedImplicitly]
		private void DeselectAll_Click(object sender, RoutedEventArgs e)
		{
			DeselectAllRequested?.Invoke(sender, e);
		}

		[UsedImplicitly]
		private void SelectByTier_Click(object sender, RoutedEventArgs e)
		{
			SelectByTierRequested?.Invoke(sender, e);
		}

		[UsedImplicitly]
		private void ClearCategorySelection_Click(object sender, RoutedEventArgs e)
		{
			ClearCategorySelectionRequested?.Invoke(sender, e);
		}

		[UsedImplicitly]
		private void ApplyCategorySelections_Click(object sender, RoutedEventArgs e)
		{
			ApplyCategorySelectionsRequested?.Invoke(sender, e);
		}
	}
}

